import { databaseSession } from "../../shared/database/databaseClient.js";
import { AppError } from "../../shared/errors/appError.js";
import type { AuthorizationService } from "../../shared/auth/authorizationService.js";
import type { ActivityRepository } from "../activity/activityRepository.js";
import type { UploadMetadataRepository } from "../upload/uploadMetadataRepository.js";
import type { InterpretationResultRepository } from "../interpretation/interpretationResultRepository.js";
import { isBlockingQuestion } from "../interpretation/interpretationReviewState.js";
import type { ProjectRepository } from "../project/projectRepository.js";
import type { ProjectLlmTokenLedgerService } from "../project/projectLlmTokenLedgerService.js";
import {
  ProjectKnowledgeModelBuildInProgressError,
  type ProjectKnowledgeBuilderService,
} from "../knowledge/projectKnowledgeBuilderService.js";
import type { DashboardCatalogAssemblerService } from "../analytics/dashboardCatalogAssemblerService.js";
import type { PythonAnalyticsCurationClient } from "../analytics/pythonAnalyticsCurationClient.js";
import { buildProjectContextForCuration } from "../analytics/projectContextForCurationBuilder.js";
import {
  REPORT_READINESS_MODEL_VERSION,
  type ReportReadinessActivityCoverage,
  type ReportReadinessCheckResult,
  type ReportReadinessOpenQuestion,
} from "../analytics/analyticsContracts.js";
import { groundReportReadinessCheckResult } from "./reportReadinessGrounding.js";

interface GatheredProjectEvidence {
  openQuestions: ReportReadinessOpenQuestion[];
  activityCoverage: ReportReadinessActivityCoverage[];
}

/**
 * Assembles the same EvidenceCatalog the analytics dashboard uses (Section 1
 * of "Phase 5 — Deterministic Analytics.md") plus two things that catalog
 * doesn't carry — pending interpretation questions and per-activity
 * evidence coverage — and asks the Python service for a structured Report
 * Readiness Check. No new evidence-gathering logic duplicates what
 * DashboardCatalogAssemblerService already does; this only adds the gap.
 */
export class ReportReadinessCheckService {
  constructor(
    private readonly authorizationService: AuthorizationService,
    private readonly activityRepository: ActivityRepository,
    private readonly uploadMetadataRepository: UploadMetadataRepository,
    private readonly interpretationResultRepository: InterpretationResultRepository,
    private readonly projectRepository: ProjectRepository,
    private readonly projectKnowledgeBuilderService: ProjectKnowledgeBuilderService,
    private readonly dashboardCatalogAssemblerService: DashboardCatalogAssemblerService,
    private readonly pythonAnalyticsCurationClient: PythonAnalyticsCurationClient,
    private readonly projectLlmTokenLedgerService: ProjectLlmTokenLedgerService,
  ) {}

  async getReportReadinessCheck(
    userId: string,
    projectId: string,
  ): Promise<ReportReadinessCheckResult> {
    const { project } = await this.authorizationService.canViewProject(
      userId,
      projectId,
    );

    const snapshot = project.reportReadinessCheckSnapshot;

    // A snapshot generated by an older prompt/schema version cannot be
    // trusted to match today's ReportReadinessCheckResult shape (Mongoose
    // stores this as an unvalidated Mixed blob — see projectModel.ts) and
    // must never be rendered as if it were current. Treat it exactly like
    // "never generated" so the caller re-runs instead of crashing on a
    // field that didn't exist yet when this snapshot was produced.
    if (
      !snapshot ||
      snapshot.reportReadinessModelVersion !== REPORT_READINESS_MODEL_VERSION
    ) {
      throw new AppError(
        "This project has no Report Readiness Check yet.",
        409,
        "report_readiness_check_not_ready",
      );
    }

    return snapshot;
  }

  async generateReportReadinessCheck(
    userId: string,
    projectId: string,
    language: "de" | "en",
  ): Promise<ReportReadinessCheckResult> {
    const { project } = await this.authorizationService.canEditProject(
      userId,
      projectId,
    );

    let { catalog, projectKnowledgeModelStatus } =
      await this.dashboardCatalogAssemblerService.assemble({
        type: "PROJECT",
        projectId,
        activityId: null,
      });

    // Same self-healing rebuild-then-reassemble as AnalyticsExecutionService
    // (analyticsExecutionService.ts) — a user running this for the first
    // time should never have to know a separate manual rebuild step exists.
    if (
      projectKnowledgeModelStatus === null ||
      projectKnowledgeModelStatus === "stale"
    ) {
      try {
        await this.projectKnowledgeBuilderService.buildForProject(projectId);
      } catch (error) {
        if (error instanceof ProjectKnowledgeModelBuildInProgressError) {
          throw this.knowledgeModelNotReadyError();
        }
        throw error;
      }
      ({ catalog, projectKnowledgeModelStatus } =
        await this.dashboardCatalogAssemblerService.assemble({
          type: "PROJECT",
          projectId,
          activityId: null,
        }));
    }

    if (projectKnowledgeModelStatus === "building") {
      throw this.knowledgeModelNotReadyError();
    }

    const { openQuestions, activityCoverage } =
      await this.gatherOpenQuestionsAndActivityCoverage(projectId);

    const projectContext = buildProjectContextForCuration(project);

    const response =
      await this.pythonAnalyticsCurationClient.generateReportReadinessCheck(
        catalog,
        projectContext,
        openQuestions,
        activityCoverage,
        language,
      );

    await this.projectLlmTokenLedgerService.recordUsage(
      projectId,
      response.llmUsage ?? null,
      databaseSession,
    );

    const grounded = groundReportReadinessCheckResult(response, catalog);

    const snapshot: ReportReadinessCheckResult = {
      overallReadiness: grounded.overallReadiness,
      evidenceSummary: grounded.evidenceSummary,
      confidentlyReportable: grounded.confidentlyReportable,
      reportableWithCaveats: grounded.reportableWithCaveats,
      missingOrWeakEvidence: grounded.missingOrWeakEvidence,
      deviationsRequiringExplanation: grounded.deviationsRequiringExplanation,
      honestEmergingStory: grounded.honestEmergingStory,
      actionsBeforeReporting: grounded.actionsBeforeReporting,
      improvementsForNextPeriod: grounded.improvementsForNextPeriod,
      groundingStatus: grounded.groundingStatus,
      groundingRetryCount: grounded.groundingRetryCount,
      reportReadinessModelVersion: grounded.reportReadinessModelVersion,
      fellBackToSelectionOnly: grounded.fellBackToSelectionOnly,
      generatedAt: new Date(),
    };

    await this.projectRepository.update(
      projectId,
      { reportReadinessCheckSnapshot: snapshot },
      databaseSession,
    );

    return snapshot;
  }

  private knowledgeModelNotReadyError(): AppError {
    return new AppError(
      "The Project Knowledge Model is already being rebuilt. Try again shortly.",
      409,
      "report_readiness_check_knowledge_model_not_ready",
    );
  }

  private async gatherOpenQuestionsAndActivityCoverage(
    projectId: string,
  ): Promise<GatheredProjectEvidence> {
    const activities = await this.activityRepository.listByProject(
      projectId,
      databaseSession,
    );
    if (activities.length === 0) {
      return { openQuestions: [], activityCoverage: [] };
    }

    const uploads = await this.uploadMetadataRepository.listByActivityIds(
      activities.map((activity) => activity.id),
      databaseSession,
    );
    const results =
      await this.interpretationResultRepository.findLatestByUploadMetadataIds(
        uploads.map((upload) => upload.id),
        databaseSession,
      );

    const uploadCountByActivityId = new Map<string, number>();
    for (const upload of uploads) {
      if (!upload.activityId) {
        continue;
      }
      uploadCountByActivityId.set(
        upload.activityId,
        (uploadCountByActivityId.get(upload.activityId) ?? 0) + 1,
      );
    }
    const resultCountByActivityId = new Map<string, number>();
    for (const result of results) {
      if (!result.activityId) {
        continue;
      }
      resultCountByActivityId.set(
        result.activityId,
        (resultCountByActivityId.get(result.activityId) ?? 0) + 1,
      );
    }

    const activityCoverage: ReportReadinessActivityCoverage[] = activities.map(
      (activity) => {
        const uploadCount = uploadCountByActivityId.get(activity.id) ?? 0;
        const resultCount = resultCountByActivityId.get(activity.id) ?? 0;
        return {
          activityId: activity.id,
          activityName: activity.name,
          isAcknowledged: activity.interpretationAcknowledgedAt !== null,
          hasFullyInterpretedEvidence:
            uploadCount > 0 && uploadCount === resultCount,
        };
      },
    );

    const activityById = new Map(
      activities.map((activity) => [activity.id, activity]),
    );
    const openQuestions: ReportReadinessOpenQuestion[] = results.flatMap(
      (result) => {
        if (!result.activityId) {
          return [];
        }
        const activity = activityById.get(result.activityId);
        if (!activity) {
          return [];
        }
        return result.questions
          .filter((question) => question.status === "pending")
          .map((question) => ({
            questionId: question.id,
            prompt: question.prompt,
            questionDomain: question.questionDomain,
            isBlocking: isBlockingQuestion(question),
            activityId: activity.id,
            activityName: activity.name,
          }));
      },
    );

    return { openQuestions, activityCoverage };
  }
}
