import type {
  IndicatorRelevanceStage,
  InterpretationEntity,
  InterpretationGoalCoverage,
  InterpretationIndicator,
  InterpretationIndicatorStatus,
  InterpretationQuestionKind,
  InterpretationQuestionStatus,
  InterpretationRelationship,
  InterpretationWarning,
  InterpretationWarningSeverity,
} from "../../shared/contracts.js";

// Mirrors the contract-level InterpretationQuestion, but with a real Date
// for answeredAt instead of an ISO string — persistence records stay in
// Date form until mapInterpretationResult() converts them for the API
// response, same as every other timestamp in this codebase.
export interface InterpretationQuestionPersistence {
  id: string;
  prompt: string;
  kind: InterpretationQuestionKind;
  options: string[] | null;
  status: InterpretationQuestionStatus;
  answeredValue: string | null;
  answeredById: string | null;
  answeredAt: Date | null;
}

export interface InterpretationResultPersistenceRecord {
  id: string;
  organizationId: string;
  projectId: string;
  activityId: string | null;
  uploadMetadataId: string;
  privacySafeRepresentationId: string;
  processingJobId: string;
  versionNumber: number;
  previousInterpretationResultId: string | null;
  datasetType: string;
  overallConfidence: number;
  entities: InterpretationEntity[];
  indicators: InterpretationIndicator[];
  relationships: InterpretationRelationship[];
  questions: InterpretationQuestionPersistence[];
  warnings: InterpretationWarning[];
  goalAlignment: InterpretationGoalCoverage[];
  createdAt: Date;
  updatedAt: Date;
}

export interface InterpretationEntityCreateInput {
  // Pre-generated by the caller (not left to the Mongoose schema default)
  // so indicators/relationships created in the same batch can reference a
  // real, stable id before the parent document is persisted.
  id: string;
  originalField: string;
  aiMeaning: string;
  entityType: string;
  confidence: number;
  reason: string;
  sampleValues: string[];
}

export interface InterpretationIndicatorCreateInput {
  // Pre-generated by the caller, same rationale as
  // InterpretationEntityCreateInput.id: goalAlignment created in the same
  // batch needs a real, stable indicator id to reference before the parent
  // document is persisted.
  id: string;
  name: string;
  description: string;
  confidence: number;
  reason: string;
  relatedEntityIds: string[];
  relevanceStage: IndicatorRelevanceStage | null;
  status: InterpretationIndicatorStatus;
}

export interface InterpretationRelationshipCreateInput {
  description: string;
  involvedEntityIds: string[];
  confidence: number;
}

export interface InterpretationQuestionCreateInput {
  prompt: string;
  kind: InterpretationQuestionKind;
  options: string[] | null;
}

export interface InterpretationWarningCreateInput {
  message: string;
  severity: InterpretationWarningSeverity;
}

export interface InterpretationGoalCoverageCreateInput {
  goalSummary: string;
  isSupportedByData: boolean;
  relatedIndicatorIds: string[];
  gapExplanation: string | null;
}

export interface InterpretationResultCreateInput {
  organizationId: string;
  projectId: string;
  activityId: string | null;
  uploadMetadataId: string;
  privacySafeRepresentationId: string;
  processingJobId: string;
  versionNumber: number;
  previousInterpretationResultId: string | null;
  datasetType: string;
  overallConfidence: number;
  entities: InterpretationEntityCreateInput[];
  indicators: InterpretationIndicatorCreateInput[];
  relationships: InterpretationRelationshipCreateInput[];
  questions: InterpretationQuestionCreateInput[];
  warnings: InterpretationWarningCreateInput[];
  goalAlignment: InterpretationGoalCoverageCreateInput[];
}

export interface InterpretationQuestionAnswerInput {
  answeredValue: string;
  answeredById: string;
  answeredAt: Date;
}
