import type {
  DatasetProfile,
  EvidenceRoutingDecision,
  InterpretationQualitativeFindingCategory,
  InterpretationQualitativeOutcomeAnchorType,
  InterpretationQuestionCode,
  IndicatorRelevanceStage,
  InterpretationEntity,
  InterpretationGoalCoverage,
  InterpretationIndicator,
  InterpretationIndicatorComputedValue,
  InterpretationIndicatorStatus,
  InterpretationIndicatorSuggestedCalculation,
  InterpretationQuestionDomain,
  InterpretationQuestionKind,
  InterpretationQuestionStatus,
  InterpretationQualitativeFindingRelation,
  InterpretationQualitativeStage,
  InterpretationRelationship,
  InterpretationQuoteExcerptKind,
  InterpretationQuotePrivacyMode,
  InterpretationQuoteSpeakerType,
  InterpretationQualitativeFinding,
  InterpretationSupportingQuote,
  InterpretationWarning,
  InterpretationWarningSeverity,
} from "../../shared/contracts.js";

// Mirrors the contract-level InterpretationQuestion, but with a real Date
// for answeredAt instead of an ISO string — persistence records stay in
// Date form until mapInterpretationResult() converts them for the API
// response, same as every other timestamp in this codebase.
export interface InterpretationQuestionPersistence {
  id: string;
  prompt: string;
  kind: InterpretationQuestionKind;
  questionDomain: InterpretationQuestionDomain;
  options: string[] | null;
  isBlocking: boolean;
  questionCode: InterpretationQuestionCode | null;
  targetTableName: string | null;
  targetColumnName: string | null;
  status: InterpretationQuestionStatus;
  answeredValue: string | null;
  answeredById: string | null;
  answeredAt: Date | null;
}

export interface InterpretationResultPersistenceRecord {
  id: string;
  organizationId: string;
  projectId: string;
  activityId: string | null;
  uploadMetadataId: string;
  privacySafeRepresentationId: string;
  processingJobId: string;
  versionNumber: number;
  previousInterpretationResultId: string | null;
  datasetType: string;
  overallConfidence: number;
  evidenceRouting: EvidenceRoutingDecision | null;
  datasetProfile: DatasetProfile | null;
  entities: InterpretationEntity[];
  indicators: InterpretationIndicator[];
  relationships: InterpretationRelationship[];
  qualitativeFindings: InterpretationQualitativeFinding[];
  supportingQuotes: InterpretationSupportingQuote[];
  questions: InterpretationQuestionPersistence[];
  warnings: InterpretationWarning[];
  goalAlignment: InterpretationGoalCoverage[];
  createdAt: Date;
  updatedAt: Date;
}

export interface InterpretationEntityCreateInput {
  // Pre-generated by the caller (not left to the Mongoose schema default)
  // so indicators/relationships created in the same batch can reference a
  // real, stable id before the parent document is persisted.
  id: string;
  originalField: string;
  aiMeaning: string;
  entityType: string;
  confidence: number;
  reason: string;
  sampleValues: string[];
}

export interface InterpretationIndicatorCreateInput {
  // Pre-generated by the caller, same rationale as
  // InterpretationEntityCreateInput.id: goalAlignment created in the same
  // batch needs a real, stable indicator id to reference before the parent
  // document is persisted.
  id: string;
  name: string;
  description: string;
  confidence: number;
  reason: string;
  relatedEntityIds: string[];
  supportingParagraphKeys: string[];
  relevanceStage: IndicatorRelevanceStage | null;
  matchesStatedGoal: boolean;
  status: InterpretationIndicatorStatus;
  suggestedCalculation: InterpretationIndicatorSuggestedCalculation | null;
  computedValue: InterpretationIndicatorComputedValue | null;
}

export interface InterpretationRelationshipCreateInput {
  description: string;
  involvedEntityIds: string[];
  confidence: number;
}

export interface InterpretationSupportingQuoteCreateInput {
  id: string;
  excerptText: string;
  excerptKind: InterpretationQuoteExcerptKind;
  speakerType: InterpretationQuoteSpeakerType;
  stage: InterpretationQualitativeStage;
  confidence: number;
  reason: string;
  sourceReference: string;
  privacyMode: InterpretationQuotePrivacyMode;
}

export interface InterpretationQualitativeFindingCreateInput {
  id: string;
  summary: string;
  stage: InterpretationQualitativeStage;
  confidence: number;
  reason: string;
  relatedEntityIds: string[];
  relatedIndicatorIds: string[];
  supportingQuoteIds: string[];
  category: InterpretationQualitativeFindingCategory;
  outcomeReference: string | null;
  outcomeAnchorType: InterpretationQualitativeOutcomeAnchorType;
  relationToEvidence: InterpretationQualitativeFindingRelation;
  status: InterpretationIndicatorStatus;
}

export interface InterpretationQuestionCreateInput {
  prompt: string;
  kind: InterpretationQuestionKind;
  questionDomain: InterpretationQuestionDomain;
  options: string[] | null;
  isBlocking: boolean;
  questionCode: InterpretationQuestionCode | null;
  targetTableName: string | null;
  targetColumnName: string | null;
}

export interface InterpretationWarningCreateInput {
  message: string;
  severity: InterpretationWarningSeverity;
}

export interface InterpretationGoalCoverageCreateInput {
  goalSummary: string;
  isSupportedByData: boolean;
  relatedIndicatorIds: string[];
  gapExplanation: string | null;
}

export interface InterpretationResultCreateInput {
  organizationId: string;
  projectId: string;
  activityId: string | null;
  uploadMetadataId: string;
  privacySafeRepresentationId: string;
  processingJobId: string;
  versionNumber: number;
  previousInterpretationResultId: string | null;
  datasetType: string;
  overallConfidence: number;
  evidenceRouting: EvidenceRoutingDecision | null;
  datasetProfile: DatasetProfile | null;
  entities: InterpretationEntityCreateInput[];
  indicators: InterpretationIndicatorCreateInput[];
  relationships: InterpretationRelationshipCreateInput[];
  qualitativeFindings: InterpretationQualitativeFindingCreateInput[];
  supportingQuotes: InterpretationSupportingQuoteCreateInput[];
  questions: InterpretationQuestionCreateInput[];
  warnings: InterpretationWarningCreateInput[];
  goalAlignment: InterpretationGoalCoverageCreateInput[];
}

export interface InterpretationResultSynthesisUpdateInput {
  datasetType: string;
  overallConfidence: number;
  entities: InterpretationEntityCreateInput[];
  indicators: InterpretationIndicatorCreateInput[];
  relationships: InterpretationRelationshipCreateInput[];
  qualitativeFindings: InterpretationQualitativeFindingCreateInput[];
  supportingQuotes: InterpretationSupportingQuoteCreateInput[];
  warnings: InterpretationWarningCreateInput[];
  goalAlignment: InterpretationGoalCoverageCreateInput[];
}

export interface InterpretationQuestionAnswerInput {
  answeredValue: string;
  answeredById: string;
  answeredAt: Date;
}
